// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/token"
	"strings"
)

type FindImporters struct{}

func (t FindImporters) Name() string { return "FindImporters" }

func (t FindImporters) Description() string {
	return `Find all Go files that import a given package path.
Input: two lines — directory path, then import path (e.g. 'fmt' or 'github.com/foo/bar').`
}

func (t FindImporters) Execute(ctx context.Context, input Input) (Output, error) {
	dir, importPath, ok := twoLines(input.Content)
	if !ok {
		return Output{Content: "Error: provide directory and import path on separate lines"}, nil
	}

	target := `"` + strings.Trim(importPath, `"`) + `"`

	fset := token.NewFileSet()
	files, err := walkGoFiles(dir, fset)
	if err != nil {
		return Output{Content: "Error: " + err.Error()}, nil
	}

	var b strings.Builder
	found := 0
	for _, f := range files {
		for _, imp := range f.Imports {
			if imp.Path.Value == target {
				fmt.Fprintf(&b, "%s\n", fset.Position(f.Pos()).Filename)
				found++
				break
			}
		}
	}

	if found == 0 {
		return Output{Content: "not found"}, nil
	}
	return Output{Content: b.String()}, nil
}
