// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

type FindCalls struct{}

func (t FindCalls) Name() string { return "FindCalls" }

func (t FindCalls) Description() string {
	return `Find all call sites of a function by name in a Go codebase.
Matches both direct calls (f()) and method calls (obj.f()).
Input: two lines — directory path, then function name (e.g. 'Println').`
}

func (t FindCalls) Execute(ctx context.Context, input Input) (Output, error) {
	dir, funcName, ok := twoLines(input.Content)
	if !ok {
		return Output{Content: "Error: provide directory and function name on separate lines"}, nil
	}

	fset := token.NewFileSet()
	files, err := walkGoFiles(dir, fset)
	if err != nil {
		return Output{Content: "Error: " + err.Error()}, nil
	}

	var b strings.Builder
	found := 0
	for _, f := range files {
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			if callFuncName(call.Fun) == funcName {
				pos := fset.Position(call.Pos())
				fmt.Fprintf(&b, "%s:%d\n", pos.Filename, pos.Line)
				found++
			}
			return true
		})
	}

	if found == 0 {
		return Output{Content: "not found"}, nil
	}
	return Output{Content: b.String()}, nil
}

func callFuncName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return e.Sel.Name
	default:
		return ""
	}
}
