// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

type FindIdent struct{}

func (t FindIdent) Name() string { return "FindIdent" }

func (t FindIdent) Description() string {
	return `Find all occurrences of an identifier by name in a Go codebase (variables, types, functions, parameters).
Input: two lines — directory path, then identifier name (e.g. 'findMe').`
}

func (t FindIdent) Execute(ctx context.Context, input Input) (Output, error) {
	dir, name, ok := twoLines(input.Content)
	if !ok {
		return Output{Content: "Error: provide directory and identifier name on separate lines"}, nil
	}

	fset := token.NewFileSet()
	files, err := walkGoFiles(dir, fset)
	if err != nil {
		return Output{Content: "Error: " + err.Error()}, nil
	}

	var b strings.Builder
	found := 0
	for _, f := range files {
		ast.Inspect(f, func(n ast.Node) bool {
			ident, ok := n.(*ast.Ident)
			if ok && ident.Name == name {
				pos := fset.Position(ident.Pos())
				fmt.Fprintf(&b, "%s:%d\n", pos.Filename, pos.Line)
				found++
			}
			return true
		})
	}

	if found == 0 {
		return Output{Content: "not found"}, nil
	}
	return Output{Content: b.String()}, nil
}
