// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

type FindImplementors struct{}

func (t FindImplementors) Name() string { return "FindImplementors" }

func (t FindImplementors) Description() string {
	return `Find all types that implement a named interface in a Go codebase.
Uses AST-level method matching (not full type-checking): a type satisfies the interface if it declares all required method names.
Input: two lines — directory path, then interface name (e.g. 'Tool').`
}

func (t FindImplementors) Execute(ctx context.Context, input Input) (Output, error) {
	dir, ifaceName, ok := twoLines(input.Content)
	if !ok {
		return Output{Content: "Error: provide directory and interface name on separate lines"}, nil
	}

	fset := token.NewFileSet()
	files, err := walkGoFiles(dir, fset)
	if err != nil {
		return Output{Content: "Error: " + err.Error()}, nil
	}

	ifaceMethods := interfaceMethods(files, ifaceName)
	if len(ifaceMethods) == 0 {
		return Output{Content: "interface not found or has no methods"}, nil
	}

	typeMethods := receiverMethods(files)

	var b strings.Builder
	fmt.Fprintf(&b, "interface %s requires: %s\n\n", ifaceName, strings.Join(sortedSet(ifaceMethods), ", "))
	found := 0
	for typeName, methods := range typeMethods {
		if covers(methods, ifaceMethods) {
			fmt.Fprintf(&b, "  %s\n", typeName)
			found++
		}
	}
	if found == 0 {
		fmt.Fprintf(&b, "  (none found)\n")
	}

	return Output{Content: b.String()}, nil
}

func interfaceMethods(files []*ast.File, ifaceName string) map[string]bool {
	methods := make(map[string]bool)
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != ifaceName {
					continue
				}
				iface, ok := ts.Type.(*ast.InterfaceType)
				if !ok {
					continue
				}
				for _, m := range iface.Methods.List {
					for _, name := range m.Names {
						methods[name.Name] = true
					}
				}
			}
		}
	}
	return methods
}

func receiverMethods(files []*ast.File) map[string]map[string]bool {
	result := make(map[string]map[string]bool)
	for _, f := range files {
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || len(fd.Recv.List) == 0 {
				continue
			}
			typeName := recvTypeName(fd.Recv.List[0].Type)
			if typeName == "" {
				continue
			}
			if result[typeName] == nil {
				result[typeName] = make(map[string]bool)
			}
			result[typeName][fd.Name.Name] = true
		}
	}
	return result
}

func recvTypeName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return recvTypeName(t.X)
	default:
		return ""
	}
}

func covers(have, need map[string]bool) bool {
	for m := range need {
		if !have[m] {
			return false
		}
	}
	return true
}

func sortedSet(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	// simple insertion sort — sets are small
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j] < keys[j-1]; j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}
