// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"
)

type ListGoPackages struct{}

func (t ListGoPackages) Name() string { return "ListGoPackages" }

func (t ListGoPackages) Description() string {
	return `List all Go packages and their source files under a directory.
Input: a directory path (e.g. '.' or 'internal/').`
}

func (t ListGoPackages) Execute(ctx context.Context, input Input) (Output, error) {
	dir := strings.TrimSpace(input.Content)
	if dir == "" {
		return Output{Content: "Error: provide a directory path"}, nil
	}

	type pkgInfo struct {
		name  string
		files []string
	}
	packages := make(map[string]*pkgInfo)

	fset := token.NewFileSet()
	filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || filepath.Ext(path) != ".go" {
			return nil
		}
		f, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}
		pkgDir := filepath.Dir(path)
		if packages[pkgDir] == nil {
			packages[pkgDir] = &pkgInfo{name: f.Name.Name}
		}
		packages[pkgDir].files = append(packages[pkgDir].files, filepath.Base(path))
		return nil
	})

	if len(packages) == 0 {
		return Output{Content: "no Go files found"}, nil
	}

	dirs := make([]string, 0, len(packages))
	for d := range packages {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	var b strings.Builder
	for _, d := range dirs {
		pkg := packages[d]
		fmt.Fprintf(&b, "package %s (%s):\n", pkg.name, d)
		for _, f := range pkg.files {
			fmt.Fprintf(&b, "  %s\n", f)
		}
	}

	return Output{Content: b.String()}, nil
}
