// NOTE: This file was generated by AI and needs to be evaluated and refactored before production use.
package tools

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
)

type ParseGoFile struct{}

func (t ParseGoFile) Name() string { return "ParseGoFile" }

func (t ParseGoFile) Description() string {
	return `
Parse a Go source file and return its structure: package name, imports, and exported declarations (functions, types, variables, constants) with their doc comments.
Input: a file path (e.g. 'internal/models/user.go').`
}

func (t ParseGoFile) Execute(ctx context.Context, input Input) (Output, error) {
	path := strings.TrimSpace(input.Content)
	if path == "" {
		return Output{Content: "Error: provide a file path"}, nil
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return Output{Content: "Error: " + err.Error()}, nil
	}

	var b strings.Builder
	fmt.Fprintf(&b, "package: %s\n", f.Name.Name)

	if len(f.Imports) > 0 {
		fmt.Fprintf(&b, "\nimports:\n")
		for _, imp := range f.Imports {
			fmt.Fprintf(&b, "  %s\n", imp.Path.Value)
		}
	}

	fmt.Fprintf(&b, "\nexported declarations:\n")
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if !d.Name.IsExported() {
				continue
			}
			doc := docString(d.Doc)
			recv := receiverString(d.Recv)
			fmt.Fprintf(&b, "  func %s%s%s\n", recv, d.Name.Name, funcParams(d.Type))
			if doc != "" {
				fmt.Fprintf(&b, "    doc: %s\n", doc)
			} else {
				fmt.Fprintf(&b, "    doc: (missing)\n")
			}
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if !s.Name.IsExported() {
						continue
					}
					doc := docString(d.Doc)
					kind := typeKind(s.Type)
					fmt.Fprintf(&b, "  type %s %s\n", s.Name.Name, kind)
					if doc != "" {
						fmt.Fprintf(&b, "    doc: %s\n", doc)
					} else {
						fmt.Fprintf(&b, "    doc: (missing)\n")
					}
				case *ast.ValueSpec:
					for _, name := range s.Names {
						if !name.IsExported() {
							continue
						}
						doc := docString(d.Doc)
						fmt.Fprintf(&b, "  %s %s\n", declToken(d.Tok.String()), name.Name)
						if doc != "" {
							fmt.Fprintf(&b, "    doc: %s\n", doc)
						} else {
							fmt.Fprintf(&b, "    doc: (missing)\n")
						}
					}
				}
			}
		}
	}

	return Output{Content: b.String()}, nil
}

func docString(cg *ast.CommentGroup) string {
	if cg == nil {
		return ""
	}
	return strings.TrimSpace(cg.Text())
}

func receiverString(fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 {
		return ""
	}
	return "(" + exprString(fl.List[0].Type) + ") "
}

func funcParams(ft *ast.FuncType) string {
	if ft == nil {
		return "()"
	}
	var params []string
	if ft.Params != nil {
		for _, p := range ft.Params.List {
			params = append(params, exprString(p.Type))
		}
	}
	sig := "(" + strings.Join(params, ", ") + ")"
	if ft.Results != nil && len(ft.Results.List) > 0 {
		var results []string
		for _, r := range ft.Results.List {
			results = append(results, exprString(r.Type))
		}
		sig += " (" + strings.Join(results, ", ") + ")"
	}
	return sig
}

func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprString(t.Elt)
	case *ast.MapType:
		return "map[" + exprString(t.Key) + "]" + exprString(t.Value)
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.StructType:
		return "struct{}"
	case *ast.Ellipsis:
		return "..." + exprString(t.Elt)
	default:
		return "..."
	}
}

func typeKind(e ast.Expr) string {
	switch e.(type) {
	case *ast.StructType:
		return "struct"
	case *ast.InterfaceType:
		return "interface"
	default:
		return exprString(e)
	}
}

func declToken(tok string) string {
	if tok == "VAR" {
		return "var"
	}
	return "const"
}
